import Project.ConnectionProvider;
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sourabh
 */
public class add extends javax.swing.JFrame {

    /**
     * Creates new form add
     */
    public add() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        fname = new javax.swing.JLabel();
        ano = new javax.swing.JLabel();
        contact = new javax.swing.JLabel();
        acctype = new javax.swing.JLabel();
        accno = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        write_name = new javax.swing.JTextField();
        write_fname = new javax.swing.JTextField();
        write_ano = new javax.swing.JTextField();
        write_contact = new javax.swing.JTextField();
        write_accno = new javax.swing.JTextField();
        write_address = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        close2 = new javax.swing.JButton();
        select_acctype = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(70, 90));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        name.setText("Name");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 147, -1));

        fname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fname.setText("Father name ");
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 147, -1));

        ano.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ano.setText("Aadhar Number");
        getContentPane().add(ano, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        contact.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        contact.setText("Contact");
        getContentPane().add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 147, -1));

        acctype.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        acctype.setText("Account type");
        getContentPane().add(acctype, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 147, -1));

        accno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        accno.setText("Account Number");
        getContentPane().add(accno, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        address.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        address.setText("Address");
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 156, -1));

        write_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(write_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 224, -1));

        write_fname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(write_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 224, -1));

        write_ano.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(write_ano, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 224, -1));

        write_contact.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(write_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 224, -1));

        write_accno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(write_accno, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 224, -1));

        write_address.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(write_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 224, -1));

        save.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.jpg"))); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, -1, -1));

        close2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        close2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close.png"))); // NOI18N
        close2.setText("close");
        close2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close2ActionPerformed(evt);
            }
        });
        getContentPane().add(close2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, -1, -1));

        select_acctype.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        select_acctype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Savings", "KCC" }));
        getContentPane().add(select_acctype, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 220, 30));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_close2ActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        String name=write_name.getText();
        String fathername=write_fname.getText();
        String aadhar=write_ano.getText();
        String contact=write_contact.getText();
        String accounttype=(String)select_acctype.getSelectedItem();
        String accountno=write_accno.getText();
        String address=write_address.getText();

        try{
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            st.executeUpdate("insert into farmer values('"+name+"','"+fathername+"','"+aadhar+"','"+contact+"','"+accounttype+"','"+accountno+"','"+address+"')");
            JOptionPane.showMessageDialog(null,"Succesfully added");
            setVisible(false);
            new add().setVisible(true);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"please enter data in correct format");
        }

    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accno;
    private javax.swing.JLabel acctype;
    private javax.swing.JLabel address;
    private javax.swing.JLabel ano;
    private javax.swing.JButton close2;
    private javax.swing.JLabel contact;
    private javax.swing.JLabel fname;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel name;
    private javax.swing.JButton save;
    private javax.swing.JComboBox<String> select_acctype;
    private javax.swing.JTextField write_accno;
    private javax.swing.JTextField write_address;
    private javax.swing.JTextField write_ano;
    private javax.swing.JTextField write_contact;
    private javax.swing.JTextField write_fname;
    private javax.swing.JTextField write_name;
    // End of variables declaration//GEN-END:variables
}
